export const ADD_FAVORITE_TO_STORE = 'ADD_FAVORITE_TO_STORE';
export const DELETE_FAVORITE_FROM_STORE = 'DELETE_FAVORITE_FROM_STORE';
export const INITIALIZE_FAVORITE_STORE = 'INITIALIZE_FAVORITE_STORE';
export const INCREASE_FAVORITE_STORE = 'INCREASE_FAVORITE_STORE';
export const DECREASE_FAVORITE_STORE = 'DECREASE_FAVORITE_STORE';
export const ADDTOBUSKET_FAVORITE_STORE = 'ADDTOBUSKET_FAVORITE_STORE';
