export const ADD_CARD_TO_BASKET = 'ADD_CARD_TO_BASKET';
export const REMOVE_CARD_IN_BASKET = 'REMOVE_CARD_IN_BASKET';

export const INCREASE_CARD_TO_BASKET = 'INCREASE_CARD_TO_BASKET';
export const DECREASE_CARD_TO_BASKET = 'DEREASE_CARD_TO_BASKET';
export const CHANGE_CARD_IN_BASKET = 'CHANGE_CARD_IN_BASKET';

export const INCREASE_TIME_CARD_TO_BASKET = 'INCREASE_TIME_CARD_TO_BASKET';
export const DECREASE_TIME_CARD_TO_BASKET = 'DEREASE_TIME_CARD_TO_BASKET';
export const CHANGE_TIME_CARD_IN_BASKET = 'CHANGE_TIME_CARD_IN_BASKET';

export const CLEAR_BASKET = 'CLEAR_BASKET';
export const INITIALIZE_SHOP = 'INITIALIZE_SHOP';
